version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: m4tsu
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: postgres_todo
      TZ: 'Asia/Tokyo'
    ports:
      - '15432:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local
